### ISSUE TITLE
Url + channel

### ISSUE THREAD

**Issue by richilp** [NDrive/nagios-mattermost#1]
Thanks for this !!

How you define the url where Mattermost is located and the channel to notify the alerts?

Thanks ;)

**Comment by andrefreitas** [comment]
Hi @richilp, you are welcome :)

You define the URL in the --url parameter as described in the [Readme](https://github.com/NDrive/nagios-mattermost/blob/master/README.md):

```
mattermost.py --url [URL] --hostalias "$HOSTNAME$" --notificationtype "$NOTIFICATIONTYPE$" --servicedesc "$SERVICEDESC$" --servicestate "$SERVICESTATE$" --serviceoutput "$SERVICEOUTPUT$"
```

Regarding the channel, URLs in Mattermost are related to a channel so I didn't add the option to set it, since Mattermost already knows it. However, I can add this possibility (maybe today)

**Comment by andrefreitas** [comment]
@richilp I have pushed a [new version](https://github.com/NDrive/nagios-mattermost/releases/tag/0.1.0) with the channel optional argument

**Comment by richilp** [comment]
Hey @andrefreitas you rock !!!!
Thank you so much !!!

**Comment by richilp** [comment]
Unfortunately I'm not beeing able to have this working.
Probably is something is my side, but I can't find it.

**bash-4.1# ./mattermost.py --url "http://localhost:8065/hooks/" --channel "xxxxxxxxxxxxxxxxxxxxxx" --hostalias "$HOSTNAME$" --notificationtype "$NOTIFICATIONTYPE$" --servicedesc "$SERVICEDESC$" --servicestate "$SERVICESTATE$" --serviceoutput "$SERVICEOUTPUT$"**
Traceback (most recent call last):
  File "./mattermost.py", line 86, in <module>
    response = request(args.url, data)
  File "./mattermost.py", line 80, in request
    response = urllib2.urlopen(req)
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(_args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(_args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

Any ideas?
Thanks !!!!

**Comment by andrefreitas** [comment]
Hi @richilp , the url you provided "http://localhost:8065/hooks/" isn't a valid one. Please use one generated by Mattermost in Incoming Webhooks. Read more at https://github.com/mattermost/platform/blob/master/doc/integrations/webhooks/Incoming-Webhooks.md

**Comment by richilp** [comment]
Thanks @andrefreitas ... we're running Nagios and Mattermost, that why I use localhost.
I've tried with the external IP with the same result :(

**Comment by andrefreitas** [comment]
Your URL is not complete, it misses the token. Use curl -X POST [URL] to test it first.

Don't forget you need to generate the URL of the Webhook in Mattermost. It's not the mattermost base URL.

**Comment by richilp** [comment]
Sorry about this. It's quite embarrasing.
I was mixing tokens and channels :(
Now is working properly

Obrigado !!!!!

**Comment by andrefreitas** [comment]
You are welcome @richilp

**Comment by henryudha** [comment]
hi @andrefreitas ,

kindly need your suggestion.
im quite struggling with your script.
i try by execute this kind of com mand : 

# ./matternag.py --url http://chat.abc.io/abc/channels/trial- --hostalias server1 --notificationtype Warning --serviceoutput "Service Apache Down!"

output is some php code.
the last line is : 
	</div>
	<script>
window.setup_login_page({"TeamDisplayName":"abc","TeamName":"abc","Title":"abc-group Chat Line - Login"});
	</script>
</body>
</html>

since our mattermost server are working well, is there anything else i need to do ?
do i need to put my username and password inside the script ?

looking forward for your information.

many thanks

cheers,
henry

**Comment by Mutha2838** [comment]
Hi,
I am running Nagios and Mattermost on Ubuntu 14.04 and i am new to Ubuntu. Can you guys please help me to integrate Nagios with MM.?
I am successful on enabling webhook URL in MM. However i am facing difficulties on  plugin installation with Nagios. So Please provide me the detailed steps on plugin installation.

Appreciate your responses.

Thanks.
